apiVersion: v1
baseDomain: DOMAIN
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: m5.2xlarge
  replicas: WORKER-REPLICAS
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: MASTER-REPLICAS
metadata:
  creationTimestamp: null
  name: NAME
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: MACHINE-NETWORK
  networkType: NETWORK-TYPE
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: REGION
    userTags: TAGS
publish: External
