apiVersion: v1
baseDomain: DOMAIN
controlPlane:
  name: master
  platform:
    ovirt:
      cpu:
        cores: 4
        sockets: 2
      memoryMB: 16384
      osDisk:
        sizeGB: 50
      vmType: server
  replicas: MASTER-REPLICAS
compute:
- name: worker
  platform:
    ovirt:
      cpu:
        cores: 4
        sockets: 4
      memoryMB: 16384
      osDisk:
        sizeGB: 50
      vmType: server
  replicas: WORKER-REPLICAS
metadata:
  name: NAME
platform:
  ovirt:
    api_vip: OVIRT-VIP-API
    ingress_vip: OVIRT-VIP-INGRESS
    dns_vip: OVIRT-VIP-DNS
    ovirt_cluster_id: OVIRT-CLUSTER
    ovirt_storage_domain_id: OVIRT-STORAGEDOMAN
    ovirt_network_name: OVIRT-NETWORK

